AWSTemplateFormatVersion: '2010-09-09'
Description: Event-driven data processing and reporting pipeline

Resources:

  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: raw-data-event-pipeline-bucket


  ProcessLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ProcessLambda
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::raw-data-event-pipeline-bucket


  ReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: daily-report-event-pipeline-bucket

  ProcessedDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProcessedSalesData
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: event-pipeline-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

  IngestLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ingest-data-lambda
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Placeholder"}

  ProcessLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: process-data-lambda
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 10
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Placeholder"}

  ReportLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: report-data-lambda
      Runtime: python3.10
      Handler: lambda_function.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 15
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return {"statusCode": 200, "body": "Placeholder"}

  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: EventIngestAPI

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: ingest

  ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaArn}/invocations
          - LambdaArn: !GetAtt IngestLambda.Arn

  ApiPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref IngestLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiMethod
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  ReportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: daily-report-topic

  ReportEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ReportSNSTopic
      Protocol: email
      Endpoint: YOUR_EMAIL@example.com

  DailyReportRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      Targets:
        - Arn: !GetAtt ReportLambda.Arn
          Id: ReportLambdaTarget

  EventBridgePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ReportLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com

  ReportLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ReportLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
